#+LANGUAGE: ru
#+AUTHOR: Вася Панков
#+ODT_STYLES_FILE: "../../templates/content12.ott"

Данное руководство преднозначено для программистов, которое подробно описывается использование программы "integrals.pank.su"\copy.

* Назначение и условия примения программ

** Назначение программы

Программа назначена для обучения интегралам.

** Функции программы

- Авторизация через telegram
- Теория в удобном формате - Markdown
- В теории предусмотрены формулы
- Существует система тестов, где вопросы в случайном порядке
- А также генерация примеров и проверка
- Синхронизация с сервером
- Просмотр профиля 

** Условия для выполнения

+ Собственный сервер
  1. Развернуть БД(PostgreSQL)
  2. Сделать telegram widget, и переноправить его на запрос
  3. Необходимо установить зависимости для Python.

     #+begin_src shell
pip install PySide2
pip install requests
     #+end_src

  4. Исправить url до сервера в в коде программы

  5. Запустить и отладить

+ При использовании установленного сервера

  1. Проверить его работоспособность перейдя по http://api.pank.su:25565

  2. Установить зависимости

     #+begin_src shell
pip install PySide2
pip install requests
     #+end_src

  3. Установить зависимости

  4. Запустить



* Характеристики программы

** Временные характеристики

Программа выполняется в зависимости от скорости вашего интернета

** Режим работы

Online - всегда необходимо подключение к интернету

** Средства контроля правильности управления 

Их нет, так как программа должна выполняться правильно и не предусматривает внутри себя случайных событий

* Обращение к программе

Обращаться программе можно лишь при запуске, но вы ничего изменить на можете.


#+begin_src shell
python main.py
#+end_src

** Обращение к серверу

Можно попробовать обращаться к серверу. 

Для этого надо уже смотреть сервер на его [[https://github.com/pank-su/RP_01/blob/master/3_server/app.py][исходный код]].

* Входные выходные данные

1. Данные аккаунта Telegram
2. Ответы на тесты и генератора примера

* Сообщения
Возможны ошибки и вылеты, связаны с интернет нестабильностью и будут выданы определённые ошибки в консоль.
 

